server:
  port: 8787

spring:
  application:
    name: ms-envio
  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5434/bdenvios
    username: postgres
    password: 12345
=======
    url: jdbc:postgresql://localhost:5437/bdenvios
    username: postgres
    password: 12345

  config:
    import: optional:configserver:http://localhost:8888

>>>>>>> 596dad4 (Cambios envios probado)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    enabled: false