version: '3'
services:

<<<<<<< HEAD
=======
  sv-gateway:
    container_name: sv-gateway
    build:
      context: ./ecommerce-gateway
    ports:
      - 8080:8080
    depends_on:
      - db-users
      - db-carts
      - db-orders
      - db-products

>>>>>>> 3771c4a24003c716f2578e958b923eb18e4b9df3

  db-users:
    container_name: db-users
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5438:5432


  db-carts:
    container_name: db-carts
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: cartdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5435:5432


  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5434:5432


  db-orders:
    container_name: db-orders
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5431:5432

  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5432

  db-payment:
    container_name: db-payment
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5436:5432








