
  server:
    port: 9096

  spring:
    application:
      name: msvc-review

    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5439/notificationdb
      username: postgres
      password: 1234

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

      logging:
        level:
          com.zaxxer.hikari: DEBUG    # muestra configuración Hikari
          org.hibernate.SQL: DEBUG     # muestra SQL DDL

    twilio:
      accountSid: YOUR_ACCOUNT_SID
      authToken: YOUR_AUTH_TOKEN
      fromPhone: YOUR_TWILIO_PHONE_NUMBER

    config:
      import: optional:configserver:http://localhost:8888

  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka


