server:
  port: 8181

spring:
  application:
    name: inventario-ms  # Identificador claro
  datasource:
    url: jdbc:postgresql://localhost:5432/bdinventario
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

# Desactiva Eureka (si no lo usas)
eureka:
  client:
    enabled: false