server:
  port: 9097

spring:
  application:
    name: msvc-review

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/reviewdb
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    logging:
      level:
        com.zaxxer.hikari: DEBUG    # muestra configuración Hikari
        org.hibernate.SQL: DEBUG     # muestra SQL DDL

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


